# database connection URL
database-url: postgres://username:password@host/schema

# deprecated, can leave blank
d1-database-url: 
d1-ops-database-url: 
d1-rejects-database-url: 

# path to data directory
data-dir: /var/daitss/data

# prefix for AIP URIs
uri-prefix: daitss://

# HTTP request expiration time in seconds
http-timeout: 600

# HTTP URLs to D2 services
actionplan-url: 
describe-url: 
viruscheck-url: 
transform-url: 
xmlresolution-url: 
storage-url: 

# specifies how many ingest processes to run at a time
throttle: 1

# outgoing SMTP server for email report delivery
smtp-server: your.smtp.server

# directives passed to the Java virtual machine, limiting maximum memory utilization
jvm-options:
- -Xms2G
- -Xmx2G
