# prefix used in minting URIs
uri-prefix: info:fcla/ # info uri prefix

# number of seconds daitss functions will wait for a service
http-timeout: 600

# database connection url
database-url: sqlite3::memory:

# workspace directory
workspace: /tmp/ws

# stash directory
stashspace: /tmp/stash

# service urls
actionplan: http://localhost:7000/actionplan
description: http://localhost:7000/description/describe
storage: http://localhost:7000/silo
viruscheck: http://localhost:7000/viruscheck/
xmlresolution: http://xmlresolution.dev.fcla.edu
submission: http://localhost:7000/submission/
request: http://localhost:7000/request/

# virus scanner
virus-scanner-executable: clamscan

# jvm options
jvm-options:
  - -Dhttp.proxyHost=sake.fcla.edu
  - -Dhttp.proxyPort=3128
  - -Xms2G
  - -Xmx2G
