# prefix used in minting URIs
uri-prefix: info:fcla/ # info uri prefix

# number of seconds daitss functions will wait for a service
http-timeout: 600

# database connection url
database-url: sqlite3::memory:

# workspace directory
workspace: /tmp

# service urls
actionplan-url: http://localhost:7000/actionplan
description-url: http://localhost:7000/description/describe
storage-url: http://localhost:7000/silo
validation-url: http://localhost:7000/validation/
xmlresolution-url: http://xmlresolution.dev.fcla.edu
submission-url: http://localhost:7000/submission/
request-url: http://localhost:7000/request/

# virus scanner
virus-scanner-executable: clamscan

# jvm options
jvm-options:
  - -Dhttp.proxyHost=sake.fcla.edu
  - -Dhttp.proxyPort=3128
  - -Xms2G
  - -Xmx2G
