database-url: sqlite:/var/daitss/database.sqlite
data: /var/daitss

uri-prefix: daitss-test
http-timeout: 600

actionplan: http://localhost:7001
describe: http://localhost:7002
storage: http://localhost:7003
statusecho: http://localhost:7004
viruscheck: http://localhost:7005
transform: http://localhost:7006
xmlresolution: http://xmlresolution.dev.fcla.edu

jvm-options:
- -Dhttp.proxyHost=sake.fcla.edu
- -Dhttp.proxyPort=3128
- -Xms2G
- -Xmx2G
