database-url: sqlite:/var/daitss/database.sqlite
data-dir: /var/daitss

uri-prefix: daitss-test
http-timeout: 600

actionplan-url: http://localhost:7001
describe-url: http://localhost:7002
storage-url: http://localhost:7003
statusecho-url: http://localhost:7004
viruscheck-url: http://localhost:7005
transform-url: http://localhost:7006
xmlresolution-url: http://xmlresolution.dev.fcla.edu

jvm-options:
- -Dhttp.proxyHost=sake.fcla.edu
- -Dhttp.proxyPort=3128
- -Xms2G
- -Xmx2G
