
# This is an example of the DAITSS configuration file restricted to
# the data necessary to run the core service.
#
# You must set up your web server to set the environment variable
# DAITSS_CONFIG to point to a configuration file along these lines,
# though typically it will have sections for many services in addition
# to this one.
#
# Please don't use tabs in this file.

defaults:
     temp_directory:             /var/tmp

database:
     daitss_db: postgres://user:pass@host/database
     daitss1_db: postgres://user:pass@host/database
    

# We normally name sections after the virtual hostname used by an
# applcation (this is so one physical host can run multiple services
# of the same kind).  An application's configuration code typically
# checks the VIRTUAL_HOSTNAME environment variable to determine the
# appropriate section to load.  Typically VIRTUAL_HOSTNAME is set in
# the same place that the DAITSS_CONFIG environment is set.

core.example.org:
    log_syslog_facility:         LOG_LOCAL0
    log_filename:                core.log

    submit_log_directory:        /path/to/submit/log
    pulse_log_filename:          /path/to/pulse/logfile
    mailer_log_filename:         /path/to/mailer/logfile

    d1_globals_dir:              /path/to/d1globals/dir

    data_dir:                    /var/daitss/data

    uri_prefix:                  daitss-test://
    http_timeout:                600

    actionplan_url:              http://url/to/actionplan
    describe_url:                http://url/to/describe
    storage_url:                 http://url/to/storemaster
    viruscheck_url:              http://url/to/viruscheck
    transform_url:               http://url/to/transform
    xmlresolution_url:           http://url/to/xmlresolution

    ingest_throttle:             2
    dissemination_throttle:      2
    d1refresh_throttle:          1
    withdrawal_throttle:         1
    queueing_discipline:         lifo

    smtp_server:                 smtp.ufl.edu

    jvm_options:
    - -Dhttp.proxyHost=sake.fcla.edu
    - -Dhttp.proxyPort=3128
    - -Xms2G
    - -Xmx2G

# defaults:temp_directory
# -----------------------
# Where should temporary files be created? This should be at least
# twice the size of the largest package you plan to ingest, plus
# headroom.  Defaults to system-defined temp directory (typically
# /tmp/)
#
# database:daitss_db
# -----------------------
# Database URL to the daitss database (typically postgres)
#
# database:daitss1_db
# -----------------------
# Database URL to the daitss1 database (only needed for D1 refresh, typically mysql

# core:log_syslog_facility
# -------------------------------
# If set, direct log information to this syslog facility (see
# /etc/syslog.conf). If neither log_filename nor log_syslog_facility
# are set, log to STDERR.
#
# core:log_filename
# -------------------------------
# If set, direct log information to this file. If neither log_filename
# nor log_syslog_facility are set, log to STDERR.
##
#
# core:log_filename
# -------------------------------
# Filesystem path to d1 global files, used for d1refresh
#
# core:submit_log_directory
# Path to write commandline submit logfiles to
#
# core:pulse_log_filename
# File to write pulse log to
#
# core:mailer_log_filename
# File to write mailer log to
#
# core:data_dir
# --------------------------
# Filesystem path to the daitss data directory
#
# core:uri_prefix
# --------------------------
# Prefix to apply to the beginning of URIs created by DAITSS
# 
# core:http_timeout
# --------------------------
# Amount of time in seconds to wait for a http request to complete
#
# core:actionplan_url
# --------------------------
# HTTP URL of actionplan service
#
# core:describe_url
# --------------------------
# HTTP URL of describe service
#
# core:storage_url
# --------------------------
# HTTP URL of storemaster service
#
# core:viruscheck_url
# --------------------------
# HTTP URL of viruscheck service
#
# core:transform_url
# --------------------------
# HTTP URL of transformation service
#
# core:xmlresolution_url
# --------------------------
# HTTP URL of xmlresolution service
#
# core:ingest-throttle
# --------------------------
# maximum number of concurrent ingest tasks to run at once
#
# core:dissemination-throttle
# --------------------------
# maximum number of concurrent dissemination tasks to run at once
#
# core:d1refresh-throttle
# --------------------------
# maximum number of concurrent d1refresh tasks to run at once
#
# core:withdrawal-throttle
# --------------------------
# maximum number of concurrent withdrawal tasks to run at once
#
# core:queueing-discipline
# --------------------------
# Valid values (lifo, fifo) order jobs are picked up to either Last In First Out (lifo) or First In First Out (fifo)
#
# core:smtp-server
# --------------------------
# URL to outgoing mail server
#
# core:jvm-options
# --------------------------
# Java options to pass to validator
