--- 
uri-prefix: daitsstest:/
actionplan-url: http://localhost:7000/actionplan/instructions
validation-url: http://localhost:7000/validation/results
provenance-url: http://localhost:7000/provenance
storage-url: http://localhost:7000/silo
description-url: http://localhost:7000/description/describe
database-uri: sqlite3:///tmp/db_sandbox
