uri-prefix: info:fcla-test
http-timeout: 600
database-url: -- overwritten by test system
data: -- overwritten by test system

actionplan: http://localhost:7000
describe: http://localhost:7001
request: http://localhost:7002
statusecho: http://localhost:7003
storage: http://localhost:7004
submission: http://localhost:7005
transform: http://localhost:7006
viruscheck: http://localhost:7007
xmlresolution: http://xmlresolution.dev.fcla.edu

# jvm options
jvm-options:
  - -Dhttp.proxyHost=sake.fcla.edu
  - -Dhttp.proxyPort=3128
  - -Xms2G
  - -Xmx2G
