defaults: &defaults
  username: daitss
  host:     localhost
  adapter: postgres

development:
  database: daitss_development
  <<: *defaults

test: &test
  database: daitss_test
  <<: *defaults

production:
  database: daitss_production
  <<: *defaults

cucumber:
  <<: *test
