defaults: &defaults
  username: franco
  host:     localhost
  adapter: postgres

development:
  database: daitss_development
  <<: *defaults

test:
  database: daitss_test
  <<: *defaults

production:
  database: daitss_production
  <<: *defaults
