defaults: &defaults
  adapter: postgres

development:
  database: db/daitss_development.db
  username: franco
  host:     localhost
  <<: *defaults

test:
  database: db/daitss_test.db
  username: franco
  host:     localhost
  <<: *defaults

production:
  database: db/daitss_production.db
  <<: *defaults
